### ISSUE TITLE
Add hyfetch

### ISSUE THREAD

**Issue by acxz** [wick3dr0se/open-system-fetch#1]
https://github.com/hykilpikonna/hyfetch

hyfetch is the currently maintained forked of neofetch, now that neofetch development is stale.

**Comment by wick3dr0se** [comment]
Looks good! I went to add it now but I'm not sure if it's Python or BASH. I know Neofetch is pure BASH, looks like hyfetch may be focusing on Python with their fork

**Comment by wick3dr0se** [comment]
I decided to put it in Python due to needing it to use hyfetch in general. Looks like a nice fetch, thanks
