### ISSUE TITLE
Add screenfetch

### ISSUE THREAD

**Issue by jdussouillez** [wick3dr0se/open-system-fetch#2]
https://github.com/KittyKatt/screenFetch

**Comment by wick3dr0se** [comment]
I have mixed feelings on this one. It's not been updated in a while and the code is really clustered. A lot of things are hard coded that shouldn't be and it's half BASH, half POSIX sh. I can't find a screenshot outside of external websites either

**Comment by wick3dr0se** [comment]
Found an SS from a seperate repo that's an installer, so I added it anyway!
